// Generated by scripts/generate-worker-env.mjs from wrangler.jsonc.
// Configuration contract: sha256-729c12ae9559a3b7
// Run "npm run generate:worker-env" after changing Worker bindings.

export interface BlogWorkerEnv {
  readonly ASSETS: Fetcher;
  readonly LOCAL_DEVELOPMENT: string;
}
