export const editorialUi = {
  en: {
    archive: "Case-study archive",
    searchLabel: "Search case studies",
    searchPlaceholder: "Search a decision, technology or project",
    typeLabel: "Filter by collection",
    all: "All",
    professional: "Professional work",
    labs: "Labs projects",
    professionalCase: "Anonymised professional case",
    labsCase: "Open-source Labs case",
    topicLabel: "Filter by topic",
    everyTopic: "Every topic",
    result: "case study",
    results: "case studies",
    clear: "Clear filters",
    emptyTitle: "No case study matches those filters.",
    emptyBody: "Try a broader phrase, another collection or every topic.",
    evidence: "Evidence ledger",
    openProject: "Open the working project",
    updated: "Updated",
  },
  it: {
    archive: "Archivio dei case study",
    searchLabel: "Cerca nei case study",
    searchPlaceholder: "Cerca una decisione, tecnologia o progetto",
    typeLabel: "Filtra per raccolta",
    all: "Tutti",
    professional: "Esperienze professionali",
    labs: "Progetti Labs",
    professionalCase: "Caso professionale anonimizzato",
    labsCase: "Caso open source di Labs",
    topicLabel: "Filtra per argomento",
    everyTopic: "Tutti gli argomenti",
    result: "case study",
    results: "case study",
    clear: "Azzera i filtri",
    emptyTitle: "Nessun case study corrisponde ai filtri.",
    emptyBody: "Prova una ricerca più ampia, un’altra raccolta o tutti gli argomenti.",
    evidence: "Registro delle evidenze",
    openProject: "Apri il progetto funzionante",
    updated: "Aggiornato",
  },
  de: {
    archive: "Fallstudien-Archiv",
    searchLabel: "Fallstudien durchsuchen",
    searchPlaceholder: "Nach Entscheidung, Technologie oder Projekt suchen",
    typeLabel: "Nach Sammlung filtern",
    all: "Alle",
    professional: "Berufliche Arbeit",
    labs: "Labs-Projekte",
    professionalCase: "Anonymisierte berufliche Fallstudie",
    labsCase: "Open-Source-Fallstudie aus Labs",
    topicLabel: "Nach Thema filtern",
    everyTopic: "Alle Themen",
    result: "Fallstudie",
    results: "Fallstudien",
    clear: "Filter zurücksetzen",
    emptyTitle: "Keine Fallstudie entspricht diesen Filtern.",
    emptyBody: "Versuchen Sie einen breiteren Begriff, eine andere Sammlung oder alle Themen.",
    evidence: "Evidenzprotokoll",
    openProject: "Funktionierendes Projekt öffnen",
    updated: "Aktualisiert",
  },
  fr: {
    archive: "Archives des études de cas",
    searchLabel: "Rechercher dans les études de cas",
    searchPlaceholder: "Rechercher une décision, une technologie ou un projet",
    typeLabel: "Filtrer par collection",
    all: "Toutes",
    professional: "Travail professionnel",
    labs: "Projets Labs",
    professionalCase: "Cas professionnel anonymisé",
    labsCase: "Étude de cas open source de Labs",
    topicLabel: "Filtrer par thème",
    everyTopic: "Tous les thèmes",
    result: "étude de cas",
    results: "études de cas",
    clear: "Effacer les filtres",
    emptyTitle: "Aucune étude de cas ne correspond à ces filtres.",
    emptyBody: "Essayez une recherche plus large, une autre collection ou tous les thèmes.",
    evidence: "Registre des preuves",
    openProject: "Ouvrir le projet fonctionnel",
    updated: "Mis à jour",
  },
};
