export const editorialUi = {
  en: {
    archive: "Engineering case-study archive",
    searchLabel: "Search case studies",
    searchPlaceholder: "Search decisions, technologies or projects",
    professionalCase: "Anonymised professional work",
    labsCase: "Open-source Labs project",
    result: "case study",
    results: "case studies",
    clear: "Clear search",
    searchLoading: "Searching the full case studies…",
    searchFallback: "Full-text search is unavailable. Showing matches from the visible summaries.",
    emptyTitle: "No case study matches that search.",
    emptyBody: "Try fewer words, or search by technology, decision or project.",
    choiceLabel: "Chosen boundary",
    whyLabel: "Why it fit",
    alternativeLabel: "Why not the obvious alternative",
    costLabel: "Cost accepted",
    tradeoffLabel: "Trade-off accepted",
    verifiedSource: "Verified source",
    verifiedOn: "Verified on",
    related: "Related case studies",
    methodology: "Editorial method",
    personal: "Djenis",
    openProject: "Visit the working project",
    updated: "Updated",
    bylineBy: "By",
    authorRole: "Engineer and case-study author",
    caseLabel: "Case",
    systemViewLabel: "System view",
    versionedDeliveryPathLabel: "Versioned delivery path",
    processStateReturnLabel: "Process state returns to the operator view",
  },
  it: {
    archive: "Archivio dei progetti di ingegneria",
    searchLabel: "Cerca nei case study",
    searchPlaceholder: "Cerca decisioni, tecnologie o progetti",
    professionalCase: "Lavoro professionale anonimizzato",
    labsCase: "Progetto Labs open source",
    result: "case study",
    results: "case study",
    clear: "Azzera la ricerca",
    searchLoading: "Ricerca nei case study completi…",
    searchFallback: "La ricerca integrale non è disponibile. Mostriamo le corrispondenze nei riepiloghi visibili.",
    emptyTitle: "Nessun case study corrisponde a questa ricerca.",
    emptyBody: "Prova con meno parole oppure cerca una tecnologia, una decisione o un progetto.",
    choiceLabel: "Scelta progettuale",
    whyLabel: "Perché era adatta",
    alternativeLabel: "Perché non l’alternativa più ovvia",
    costLabel: "Costo accettato",
    tradeoffLabel: "Compromesso accettato",
    verifiedSource: "Fonte verificata",
    verifiedOn: "Verificata il",
    related: "Case study correlati",
    methodology: "Metodo editoriale",
    personal: "Djenis",
    openProject: "Visita il progetto funzionante",
    updated: "Aggiornato",
    bylineBy: "Di",
    authorRole: "Ingegnere e autore del case study",
    caseLabel: "Caso",
    systemViewLabel: "Vista del sistema",
    versionedDeliveryPathLabel: "Percorso di delivery versionato",
    processStateReturnLabel: "Lo stato del processo ritorna alla vista operatore",
  },
  de: {
    archive: "Archiv der Engineering-Fallstudien",
    searchLabel: "Fallstudien durchsuchen",
    searchPlaceholder: "Entscheidungen, Technologien oder Projekte suchen",
    professionalCase: "Anonymisierte berufliche Arbeit",
    labsCase: "Open-Source-Projekt aus Labs",
    result: "Fallstudie",
    results: "Fallstudien",
    clear: "Suche löschen",
    searchLoading: "Vollständige Fallstudien werden durchsucht…",
    searchFallback: "Die Volltextsuche ist nicht verfügbar. Angezeigt werden Treffer aus den sichtbaren Zusammenfassungen.",
    emptyTitle: "Keine Fallstudie passt zu dieser Suche.",
    emptyBody: "Versuchen Sie weniger Wörter oder suchen Sie nach Technologie, Entscheidung oder Projekt.",
    choiceLabel: "Gewählte Systemgrenze",
    whyLabel: "Warum sie passte",
    alternativeLabel: "Warum nicht die naheliegende Alternative",
    costLabel: "Akzeptierter Preis",
    tradeoffLabel: "Akzeptierter Zielkonflikt",
    verifiedSource: "Geprüfte Quelle",
    verifiedOn: "Geprüft am",
    related: "Ähnliche Fallstudien",
    methodology: "Redaktionelle Methode",
    personal: "Djenis",
    openProject: "Funktionierendes Projekt ansehen",
    updated: "Aktualisiert",
    bylineBy: "Von",
    authorRole: "Softwareingenieur und Autor der Fallstudie",
    caseLabel: "Fall",
    systemViewLabel: "Systemansicht",
    versionedDeliveryPathLabel: "Versionierter Auslieferungspfad",
    processStateReturnLabel: "Der Prozessstatus kehrt zur Bedienansicht zurück",
  },
  fr: {
    archive: "Archives des projets d’ingénierie",
    searchLabel: "Rechercher dans les études de cas",
    searchPlaceholder: "Rechercher des décisions, technologies ou projets",
    professionalCase: "Travail professionnel anonymisé",
    labsCase: "Projet Labs open source",
    result: "étude de cas",
    results: "études de cas",
    clear: "Effacer la recherche",
    searchLoading: "Recherche dans les études de cas complètes…",
    searchFallback: "La recherche intégrale est indisponible. Les résultats affichés proviennent des résumés visibles.",
    emptyTitle: "Aucune étude de cas ne correspond à cette recherche.",
    emptyBody: "Essayez moins de mots ou recherchez une technologie, une décision ou un projet.",
    choiceLabel: "Choix d’architecture",
    whyLabel: "Pourquoi il convenait",
    alternativeLabel: "Pourquoi pas l’alternative évidente",
    costLabel: "Coût accepté",
    tradeoffLabel: "Compromis accepté",
    verifiedSource: "Source vérifiée",
    verifiedOn: "Vérifiée le",
    related: "Études de cas associées",
    methodology: "Méthode éditoriale",
    personal: "Djenis",
    openProject: "Voir le projet fonctionnel",
    updated: "Mis à jour",
    bylineBy: "Par",
    authorRole: "Ingénieur et auteur de l’étude",
    caseLabel: "Cas",
    systemViewLabel: "Vue du système",
    versionedDeliveryPathLabel: "Parcours de livraison versionné",
    processStateReturnLabel: "L’état du processus revient à la vue opérateur",
  },
};

export const methodology = Object.freeze({
  published: "2026-07-25",
  updated: "2026-07-28",
  copy: {
    en: {
      eyebrow: "Editorial methodology",
      title: "How this archive is built",
      description: "How Ejupi Labs handles evidence, technical rationale, anonymisation and corrections across the case-study archive.",
      intro: "Each article separates what was built from why it was built that way: the constraint, the chosen boundary, the credible alternative and the cost accepted.",
      sections: [
        {
          id: "labs-evidence",
          title: "Labs evidence",
          paragraphs: [
            "Every Labs case study points to a public, immutable GitHub commit. Before publication, I check version references, test results and implementation details against that exact snapshot.",
            "The working product page remains the primary project link. The evidence ledger records what I verified and where each claim stops.",
            "Technology comparisons are contextual, not rankings. A choice is explained against the product’s actual constraints and the strongest plausible alternative, including the complexity or limitation it deliberately keeps.",
          ],
        },
        {
          id: "professional-anonymisation",
          title: "Professional work",
          paragraphs: [
            "In the professional case studies, I describe engineering work I delivered in employment roles. I withhold company and client names, commercial terms, private repositories and identifying operational data.",
            "I keep the technical sequence, decisions and constraints faithful. I leave out metrics or outcomes that I cannot support without exposing confidential information.",
            "Where implementation details must remain private, I explain the decision boundary without implying access to evidence I cannot publish. The rationale stays specific; confidential identifiers do not.",
          ],
        },
        {
          id: "corrections",
          title: "Corrections",
          paragraphs: [
            "If a factual detail is wrong or no longer current, email info@ejupilabs.com. I review the source, correct the article and update its verification date.",
          ],
        },
      ],
      contactLabel: "Report a correction",
    },
    it: {
      eyebrow: "Metodologia editoriale",
      title: "Come viene costruito questo archivio",
      description: "Come Ejupi Labs gestisce evidenze, motivazioni tecniche, anonimizzazione e correzioni nell’archivio dei case study.",
      intro: "Ogni articolo separa ciò che è stato costruito dal perché è stato costruito così: il vincolo, la scelta, l’alternativa credibile e il costo accettato.",
      sections: [
        {
          id: "labs-evidence",
          title: "Evidenze dei progetti Labs",
          paragraphs: [
            "Ogni case study Labs rimanda a un commit GitHub pubblico e immutabile. Prima della pubblicazione verifico versioni, risultati dei test e dettagli implementativi su quello snapshot preciso.",
            "La pagina del prodotto funzionante resta il link principale del progetto. Il registro delle evidenze indica cosa ho verificato e dove si ferma ogni affermazione.",
            "I confronti tra tecnologie sono contestuali, non classifiche assolute. Ogni scelta viene valutata rispetto ai vincoli reali del prodotto e all’alternativa più credibile, dichiarando anche la complessità o il limite che conserva.",
          ],
        },
        {
          id: "professional-anonymisation",
          title: "Lavoro professionale",
          paragraphs: [
            "Nei case study professionali descrivo attività di ingegneria svolte in ruoli dipendenti. Ometto nomi di aziende e clienti, condizioni commerciali, repository privati e dati operativi identificativi.",
            "Mantengo fedeli la sequenza tecnica, le decisioni e i vincoli. Escludo metriche o risultati che non potrei documentare senza rivelare informazioni confidenziali.",
            "Quando i dettagli implementativi devono restare privati, spiego il confine della decisione senza suggerire evidenze che non posso pubblicare. La motivazione resta specifica; gli identificativi riservati no.",
          ],
        },
        {
          id: "corrections",
          title: "Correzioni",
          paragraphs: [
            "Se un dettaglio è errato o non è più attuale, scrivi a info@ejupilabs.com. Verifico la fonte, correggo l’articolo e aggiorno la data di verifica.",
          ],
        },
      ],
      contactLabel: "Segnala una correzione",
    },
    de: {
      eyebrow: "Redaktionelle Methodik",
      title: "Wie dieses Archiv entsteht",
      description: "Wie Ejupi Labs im Fallstudien-Archiv mit Nachweisen, technischen Begründungen, Anonymisierung und Korrekturen umgeht.",
      intro: "Jeder Beitrag trennt das Ergebnis von seiner Begründung: Einschränkung, gewählte Systemgrenze, tragfähige Alternative und bewusst akzeptierter Preis.",
      sections: [
        {
          id: "labs-evidence",
          title: "Nachweise für Labs-Projekte",
          paragraphs: [
            "Jede Labs-Fallstudie verweist auf einen öffentlichen, unveränderlichen GitHub-Commit. Vor der Veröffentlichung prüfe ich Versionsangaben, Testergebnisse und Implementierungsdetails gegen genau diesen Stand.",
            "Die funktionierende Produktseite bleibt der primäre Projektlink. Das Evidenzprotokoll zeigt, was ich geprüft habe und wo die jeweilige Aussage endet.",
            "Technologievergleiche sind kontextbezogen und keine allgemeine Rangliste. Jede Wahl wird an den tatsächlichen Produktanforderungen und der stärksten realistischen Alternative gemessen – einschließlich der bewusst verbleibenden Komplexität oder Grenze.",
          ],
        },
        {
          id: "professional-anonymisation",
          title: "Berufliche Arbeit",
          paragraphs: [
            "In den beruflichen Fallstudien beschreibe ich Entwicklungsarbeit aus meinen Anstellungsverhältnissen. Unternehmens- und Kundennamen, Konditionen, private Repositories und identifizierende Betriebsdaten lasse ich weg.",
            "Technischen Ablauf, Entscheidungen und Einschränkungen gebe ich sachlich korrekt wieder. Kennzahlen oder Ergebnisse, die sich nur durch vertrauliche Angaben belegen ließen, veröffentliche ich nicht.",
            "Wenn Implementierungsdetails vertraulich bleiben müssen, erkläre ich die Entscheidungsgrenze, ohne nicht veröffentlichbare Belege anzudeuten. Die Begründung bleibt konkret, geschützte Identifikatoren nicht.",
          ],
        },
        {
          id: "corrections",
          title: "Korrekturen",
          paragraphs: [
            "Wenn eine Angabe falsch oder nicht mehr aktuell ist, schreiben Sie an info@ejupilabs.com. Ich prüfe die Quelle, korrigiere den Beitrag und aktualisiere das Prüfdatum.",
          ],
        },
      ],
      contactLabel: "Korrektur melden",
    },
    fr: {
      eyebrow: "Méthodologie éditoriale",
      title: "Comment ces archives sont construites",
      description: "Comment Ejupi Labs traite les preuves, les raisons techniques, l’anonymisation et les corrections dans ses études de cas.",
      intro: "Chaque article distingue ce qui a été construit de la raison du choix : contrainte, option retenue, alternative crédible et coût accepté.",
      sections: [
        {
          id: "labs-evidence",
          title: "Preuves des projets Labs",
          paragraphs: [
            "Chaque étude de cas Labs renvoie vers un commit GitHub public et immuable. Avant publication, je vérifie les versions, les résultats de tests et les détails d’implémentation sur cet instantané précis.",
            "La page du produit fonctionnel reste le lien principal du projet. Le registre des preuves indique ce que j’ai vérifié et où s’arrête chaque affirmation.",
            "Les comparaisons technologiques dépendent du contexte : ce ne sont pas des classements absolus. Chaque choix est évalué selon les contraintes réelles du produit et l’alternative la plus crédible, en exposant aussi la complexité ou la limite volontairement conservée.",
          ],
        },
        {
          id: "professional-anonymisation",
          title: "Travail professionnel",
          paragraphs: [
            "Dans les études de cas professionnelles, je décris le travail d’ingénierie réalisé dans le cadre de mes emplois. Je retire les noms d’entreprises et de clients, les conditions commerciales, les dépôts privés et les données d’exploitation identifiantes.",
            "Je restitue fidèlement la séquence technique, les décisions et les contraintes. J’écarte les métriques ou résultats que je ne pourrais pas étayer sans révéler d’informations confidentielles.",
            "Lorsque les détails d’implémentation doivent rester privés, j’explique la frontière de décision sans laisser entendre l’existence de preuves que je ne peux pas publier. Le raisonnement reste précis, les identifiants confidentiels non.",
          ],
        },
        {
          id: "corrections",
          title: "Corrections",
          paragraphs: [
            "Si un détail est erroné ou n’est plus à jour, écrivez à info@ejupilabs.com. Je vérifie la source, corrige l’article et actualise sa date de vérification.",
          ],
        },
      ],
      contactLabel: "Signaler une correction",
    },
  },
});
